### ISSUE TITLE
[question] i wander what's the normal speed of sglang at a 8 * a800 machine.

### ISSUE THREAD

**Issue by guox18** [sgl-project/sglang#2246] opened 2024-11-28 15:35 UTC
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

yes, i only have a 8*a800 machine. i set the 8 request threads, tp 8, with a 70b model like llama3.1
the final throughput is about 500 tokens/second

i wander is this speed normal.

by the way, can anyone show me the way to slack channel of sglang?  i hear that this channel is active

(i want to use a100. cry)

### Reproduction

0

### Environment

0

**Comment by guox18** [comment] 2024-11-28 15:36
i can provider more info needed if anyone can help me. thanks a lot.

**Comment by merrymercy** [comment] 2024-12-01 10:21
Can you paste reproducible commands?
You can join the channel at  https://join.slack.com/t/sgl-fru7574/shared_invite/zt-2um0ad92q-LkU19KQTxCGzlCgRiOiQEw
I will close this one since this is not a bug report or feature request.

**Closed by merrymercy** 2024-12-01 10:21 UTC
