### ISSUE TITLE
[Bug] OOM when runing `bench_serving` with DeepSeekCoder-V2-Lite.

### ISSUE THREAD

**Issue by zh-zheng** [sgl-project/sglang#1455] opened 2024-09-18 10:14 UTC
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [X] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [X] 5. Please use English, otherwise it will be closed.

### Describe the bug

I install the main branch of SGLang(commit id: 7c162fa), and run `bench_serving` according to your [blog](https://lmsys.org/blog/2024-09-04-sglang-v0-3/). 

The command is:
`python3 -m sglang.launch_server --model ./DeepSeek-Coder-V2-Lite-Instruct --trust-remote-code`

`python3 -m sglang.bench_serving --backend sglang --num-prompts 5000  --dataset-path ./ShareGPT_V3_unfiltered_cleaned_split.json`

However, I keep encountering a "CUDA out of memory" error, preventing the process from completing all 5000 prompts.

### Reproduction

Traceback:
`
![image](https://github.com/user-attachments/assets/9c6b14a9-204e-495f-a118-a651f5f299b5)
`

### Environment

```
Python: 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.3, V12.3.107
CUDA Driver Version: 470.161.03
PyTorch: 2.4.0+cu121
sglang: 0.3.1.post1
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.3
fastapi: 0.115.0
hf_transfer: 0.1.8
huggingface_hub: 0.25.0
interegular: 0.3.3
packaging: 23.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.9.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.2.0
vllm: 0.5.5
multipart: 0.0.9
openai: 1.46.0
anthropic: 0.34.2
NVIDIA Topology:
	GPU0	GPU1	GPU2	GPU3	GPU4	GPU5	GPU6	GPU7	mlx5_0	mlx5_1	mlx5_2	mlx5_3	mlx5_4	mlx5_5	mlx5_6	mlx5_7	mlx5_8	CPU Affinity	NUMA Affinity
GPU0	 X 	NV12	NV12	NV12	NV12	NV12	NV12	NV12	NODE	PXB	PXBNODE	NODE	SYS	SYS	SYS	SYS	0-31,64-95	0
GPU1	NV12	 X 	NV12	NV12	NV12	NV12	NV12	NV12	NODE	PXB	PXBNODE	NODE	SYS	SYS	SYS	SYS	0-31,64-95	0
GPU2	NV12	NV12	 X 	NV12	NV12	NV12	NV12	NV12	NODE	NODE	NODE	PXB	PXB	SYS	SYS	SYS	SYS	0-31,64-95	0
GPU3	NV12	NV12	NV12	 X 	NV12	NV12	NV12	NV12	NODE	NODE	NODE	PXB	PXB	SYS	SYS	SYS	SYS	0-31,64-95	0
GPU4	NV12	NV12	NV12	NV12	 X 	NV12	NV12	NV12	SYS	SYS	SYSSYS	SYS	PXB	PXB	NODE	NODE	32-63,96-127	1
GPU5	NV12	NV12	NV12	NV12	NV12	 X 	NV12	NV12	SYS	SYS	SYSSYS	SYS	PXB	PXB	NODE	NODE	32-63,96-127	1
GPU6	NV12	NV12	NV12	NV12	NV12	NV12	 X 	NV12	SYS	SYS	SYSSYS	SYS	NODE	NODE	PXB	PXB	32-63,96-127	1
GPU7	NV12	NV12	NV12	NV12	NV12	NV12	NV12	 X 	SYS	SYS	SYSSYS	SYS	NODE	NODE	PXB	PXB	32-63,96-127	1
mlx5_0	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS	 X 	NODE	NODE	NODE	NODE	SYS	SYS	SYS	SYS
mlx5_1	PXB	PXB	NODE	NODE	SYS	SYS	SYS	SYS	NODE	 X 	PIXNODE	NODE	SYS	SYS	SYS	SYS
mlx5_2	PXB	PXB	NODE	NODE	SYS	SYS	SYS	SYS	NODE	PIX	 X NODE	NODE	SYS	SYS	SYS	SYS
mlx5_3	NODE	NODE	PXB	PXB	SYS	SYS	SYS	SYS	NODE	NODE	NODE	 X 	PIX	SYS	SYS	SYS	SYS
mlx5_4	NODE	NODE	PXB	PXB	SYS	SYS	SYS	SYS	NODE	NODE	NODE	PIX	 X 	SYS	SYS	SYS	SYS
mlx5_5	SYS	SYS	SYS	SYS	PXB	PXB	NODE	NODE	SYS	SYS	SYSSYS	SYS	 X 	PIX	NODE	NODE
mlx5_6	SYS	SYS	SYS	SYS	PXB	PXB	NODE	NODE	SYS	SYS	SYSSYS	SYS	PIX	 X 	NODE	NODE
mlx5_7	SYS	SYS	SYS	SYS	NODE	NODE	PXB	PXB	SYS	SYS	SYSSYS	SYS	NODE	NODE	 X 	PIX
mlx5_8	SYS	SYS	SYS	SYS	NODE	NODE	PXB	PXB	SYS	SYS	SYSSYS	SYS	NODE	NODE	PIX	 X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

ulimit soft: 1024
```

**Comment by merrymercy** [comment] 2024-09-18 10:51
Thanks for reporting. The batch size is too large for this config so you see OOM during the decoding.
you can use 
```
python3 -m sglang.launch_server --model ./DeepSeek-Coder-V2-Lite-Instruct --trust-remote-code --max-running-requests 2560
```

In the meantime, we will make the default parameters more robust.

**Comment by merrymercy** [comment] 2024-09-18 11:14
There are some regressions on the memory usage. I am investigating it right now.

To reproduce the results in the blog, you can `git checkout v0.3.0`.

We will push some fixes to the main very soon. Or you can wait until we pushed the fixes.

**Comment by merrymercy** [comment] 2024-09-18 11:41
Thanks for reporting. I confirmed that the OOM is due to enabling the Cuda graph for the triton attention backend (https://github.com/sgl-project/sglang/pull/1401). That PR is after v0.3.0, so the old command in the blog now causes OOM.
There are multiple ways to reproduce the results with the current main branch (commit: 7f24ea95c344)


### Method 1: disable cuda graph. It can run the full 5000 prompts with a maximum batch size of around 3500. The final speed is 32.34 req/s on an H100.
```
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct --trust-remote-code --disable-cuda-graph
```

### Method 2: enable cuda graph but limit the batch size. The final speed is 33.68 req/s on an H100, so this method is faster.
```
python3 -m sglang.launch_server --model deepseek-ai/DeepSeek-Coder-V2-Lite-Instruct --trust-remote-code --max-running-request 2560
```

We will make the default settings more robust in the future so you can just run with the default arguments.

**Closed** 2024-09-18 11:42 UTC

**Comment by zh-zheng** [comment] 2024-09-18 13:10
For current version, is it possible to enable cuda graph without limit the batch size?

**Comment by merrymercy** [comment] 2024-09-22 10:42
It is not possible. batch size 2560 is already very large. This is the limit of the memory capacity, given the current parallelism strategy.
However, as [discussed](https://docs.google.com/presentation/d/1wB_Ul0LZwIDL47qFl64b8hVhH1_ya-1YPAPSSv0cKMs) in our weekly meeting today, we will work on more optimizations to support a larger batch size.
