### ISSUE TITLE
[Bug] RuntimeError in ModelTpServer

### ISSUE THREAD

**Issue by Lzhang-hub** [sgl-project/sglang#1323] opened 2024-09-04 08:05 UTC
### Checklist

- [ ] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.
- [ ] 4. If the issue you raised is not a bug but a question, please raise a discussion at https://github.com/sgl-project/sglang/discussions/new/choose Otherwise, it will be closed.
- [ ] 5. Please use English, otherwise it will be closed.

### Describe the bug

benchmark serving got error when --num-prompts=5
num-prompts=1 and num-prompts=3 work fine, failed when num-prompts=5
```
Exception in ModelTpServer:
Traceback (most recent call last):
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 218, in exposed_step
    self.forward_step()
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 234, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 446, in forward_prefill_batch
    output = self.model_runner.forward(batch, ForwardMode.EXTEND)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 430, in forward
    return self.forward_extend(batch)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 399, in forward_extend
    input_metadata = InputMetadata.from_schedule_batch(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/forward_batch_info.py", line 200, in from_schedule_batch
    ret.init_flashinfer_handlers(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/forward_batch_info.py", line 225, in init_flashinfer_handlers
    update_flashinfer_indices(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/forward_batch_info.py", line 315, in update_flashinfer_indices
    model_runner.flashinfer_prefill_wrapper_paged.begin_forward(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/flashinfer/prefill.py", line 804, in begin_forward
    self._wrapper.begin_forward(
RuntimeError: Failed to allocate memory for batch_prefill_tmp_v with size 450494464 and alignment 16 in AlignedAllocator

Exception in ControllerSingle:
Traceback (most recent call last):
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/controller_single.py", line 166, in start_controller_process
    controller.loop_for_forward()
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/controller_single.py", line 103, in loop_for_forward
    out_pyobjs = self.tp_server.exposed_step(recv_reqs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 218, in exposed_step
    self.forward_step()
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 234, in forward_step
    self.forward_prefill_batch(new_batch)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/managers/tp_worker.py", line 446, in forward_prefill_batch
    output = self.model_runner.forward(batch, ForwardMode.EXTEND)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 430, in forward
    return self.forward_extend(batch)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/model_runner.py", line 399, in forward_extend
    input_metadata = InputMetadata.from_schedule_batch(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/forward_batch_info.py", line 200, in from_schedule_batch
    ret.init_flashinfer_handlers(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/forward_batch_info.py", line 225, in init_flashinfer_handlers
    update_flashinfer_indices(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/sglang/srt/model_executor/forward_batch_info.py", line 315, in update_flashinfer_indices
    model_runner.flashinfer_prefill_wrapper_paged.begin_forward(
  File "/data1/nfs15/nfs/bigdata/zhanglei/conda/envs/sglang-0.2.13/lib/python3.10/site-packages/flashinfer/prefill.py", line 804, in begin_forward
    self._wrapper.begin_forward(
RuntimeError: Failed to allocate memory for batch_prefill_tmp_v with size 450494464 and alignment 16 in AlignedAllocator
```

### Reproduction

server:
```
python -m sglang.launch_server --model-path Qwen/Qwen2-7B-Instruct --tensor-parallel-size 1 --disable-radix-cache --host 0.0.0.0 --port 8083  --trust-remote-code --served-model-name Qwen2-7B-Instruct --mem-fraction-static 0.9
```
benchmark:
```
python benchmark_serving.py --model Qwen2-7B-Instruct --tokenizer Qwen/Qwen2-7B-Instruct  --host 0.0.0.0 --port 8083 --dataset-name random --random-input-len 4096 --random-output-len 256 --save-result --num-prompts 5
```

### Environment

Python: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA A100-SXM4-80GB
GPU 0,1,2,3,4,5,6,7 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 525.85.12
PyTorch: 2.4.0+cu121
sglang: 0.2.13
flashinfer: 0.1.5+cu121torch2.4
triton: 3.0.0
transformers: 4.44.0
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.4
aiohttp: 3.10.5
fastapi: 0.112.1
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 24.1
PIL: 10.4.0
psutil: 6.0.0
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 26.1.1
vllm: 0.5.4
multipart: 0.0.9
openai: 1.41.1
anthropic: 0.34.1
NVIDIA Topology: 
        GPU0    GPU1    GPU2    GPU3    GPU4    GPU5    GPU6    GPU7    NIC0    NIC1NIC2    NIC3    NIC4    NIC5    NIC6    NIC7    NIC8    CPU Affinity    NUMA Affinity
GPU0     X      NV12    NV12    NV12    NV12    NV12    NV12    NV12    PXB     PXBNODE     NODE    SYS     SYS     SYS     SYS     SYS     0-31,64-95      0
GPU1    NV12     X      NV12    NV12    NV12    NV12    NV12    NV12    PXB     PXBNODE     NODE    SYS     SYS     SYS     SYS     SYS     0-31,64-95      0
GPU2    NV12    NV12     X      NV12    NV12    NV12    NV12    NV12    NODE    NODEPXB     PXB     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0
GPU3    NV12    NV12    NV12     X      NV12    NV12    NV12    NV12    NODE    NODEPXB     PXB     SYS     SYS     SYS     SYS     SYS     0-31,64-95      0
GPU4    NV12    NV12    NV12    NV12     X      NV12    NV12    NV12    SYS     SYSSYS      SYS     PXB     PXB     NODE    NODE    NODE    32-63,96-127    1
GPU5    NV12    NV12    NV12    NV12    NV12     X      NV12    NV12    SYS     SYSSYS      SYS     PXB     PXB     NODE    NODE    NODE    32-63,96-127    1
GPU6    NV12    NV12    NV12    NV12    NV12    NV12     X      NV12    SYS     SYSSYS      SYS     NODE    NODE    PXB     PXB     NODE    32-63,96-127    1
GPU7    NV12    NV12    NV12    NV12    NV12    NV12    NV12     X      SYS     SYSSYS      SYS     NODE    NODE    PXB     PXB     NODE    32-63,96-127    1
NIC0    PXB     PXB     NODE    NODE    SYS     SYS     SYS     SYS      X      PIXNODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC1    PXB     PXB     NODE    NODE    SYS     SYS     SYS     SYS     PIX      X NODE     NODE    SYS     SYS     SYS     SYS     SYS
NIC2    NODE    NODE    PXB     PXB     SYS     SYS     SYS     SYS     NODE    NODE X      PIX     SYS     SYS     SYS     SYS     SYS
NIC3    NODE    NODE    PXB     PXB     SYS     SYS     SYS     SYS     NODE    NODEPIX      X      SYS     SYS     SYS     SYS     SYS
NIC4    SYS     SYS     SYS     SYS     PXB     PXB     NODE    NODE    SYS     SYSSYS      SYS      X      PIX     NODE    NODE    NODE
NIC5    SYS     SYS     SYS     SYS     PXB     PXB     NODE    NODE    SYS     SYSSYS      SYS     PIX      X      NODE    NODE    NODE
NIC6    SYS     SYS     SYS     SYS     NODE    NODE    PXB     PXB     SYS     SYSSYS      SYS     NODE    NODE     X      PIX     NODE
NIC7    SYS     SYS     SYS     SYS     NODE    NODE    PXB     PXB     SYS     SYSSYS      SYS     NODE    NODE    PIX      X      NODE
NIC8    SYS     SYS     SYS     SYS     NODE    NODE    NODE    NODE    SYS     SYSSYS      SYS     NODE    NODE    NODE    NODE     X 

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_0
  NIC1: mlx5_1
  NIC2: mlx5_2
  NIC3: mlx5_3
  NIC4: mlx5_6
  NIC5: mlx5_7
  NIC6: mlx5_8
  NIC7: mlx5_9
  NIC8: mlx5_bond_0

ulimit soft: 65536

**Comment by zhyncs** [comment] 2024-09-04 08:07
try the latest version 0.3.0

**Comment by Lzhang-hub** [comment] 2024-09-04 08:08
ok

**Comment by Lzhang-hub** [comment] 2024-09-04 08:55
@zhyncs 0.3.0 got same error

**Comment by zhyncs** [comment] 2024-09-04 08:58
Ok I’ll take a look asap.

**Comment by zhyncs** [comment] 2024-09-04 09:19
```
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
CUDA available: True
GPU 0: NVIDIA A100-SXM4-80GB
GPU 0 Compute Capability: 8.0
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 12.1, V12.1.105
CUDA Driver Version: 535.104.05
PyTorch: 2.4.0+cu121
flashinfer: 0.1.6+cu121torch2.4
triton: 3.0.0
transformers: 4.44.2
requests: 2.32.3
tqdm: 4.66.5
numpy: 1.26.3
aiohttp: 3.10.5
fastapi: 0.112.2
hf_transfer: 0.1.8
huggingface_hub: 0.24.6
interegular: 0.3.3
packaging: 23.2
PIL: 10.2.0
psutil: 5.9.8
pydantic: 2.8.2
uvicorn: 0.30.6
uvloop: 0.20.0
zmq: 24.0.1
vllm: 0.5.5
multipart: 0.0.9
openai: 1.43.0
anthropic: 0.34.1
NVIDIA Topology:
        GPU0    NIC0    NIC1    CPU Affinity    NUMA Affinity   GPU NUMA ID
GPU0     X      SYS     PXB     48-63,176-191   3               N/A
NIC0    SYS      X      SYS
NIC1    PXB     SYS      X

Legend:

  X    = Self
  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)
  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node
  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)
  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)
  PIX  = Connection traversing at most a single PCIe bridge
  NV#  = Connection traversing a bonded set of # NVLinks

NIC Legend:

  NIC0: mlx5_bond_0
  NIC1: mlx5_bond_1


ulimit soft: 1048576
```

```
python -m sglang.launch_server --model-path Qwen/Qwen2-7B-Instruct --tensor-parallel-size 1 --disable-radix-cache --host 0.0.0.0 --port 8083  --trust-remote-code --served-model-name Qwen2-7B-Instruct --mem-fraction-static 0.9

python3 -m sglang.bench_serving --model Qwen2-7B-Instruct --tokenizer Qwen/Qwen2-7B-Instruct  --host 0.0.0.0 --port 8083 --dataset-name random --random-input-len 4096 --random-output-len 256 --num-prompts 5
```

It works well for me and I can't reproduce your issue. Maybe you can try docker https://github.com/sgl-project/sglang/?tab=readme-ov-file#method-3-using-docker

**Comment by Lzhang-hub** [comment] 2024-09-04 12:40
@zhyncs I got same error when use docker images https://github.com/sgl-project/sglang/?tab=readme-ov-file#method-3-using-docker

**Comment by zhyncs** [comment] 2024-09-04 15:41
It's a little wired. May you start a new instance, eliminating the environmental issues of the machine itself. And try this
```bash
pip install --upgrade pip
pip install "sglang[all]"

# Install FlashInfer CUDA kernels
pip install flashinfer -i https://flashinfer.ai/whl/cu121/torch2.4/
```

**Comment by dmakhervaks** [comment] 2024-09-04 23:06
I am getting the same issue:

![image](https://github.com/user-attachments/assets/bdde59b3-bebb-49c1-bf35-3aabddb4b7bb)

I launched the server like this:
`python3 -m sglang.launch_server --model-path $model_arg --tp 8 --disable-radix-cache --host 0.0.0.0 --port 9942 --log-level debug --file-storage-pth /home/dave.makhervaks/SGl
ang_storage --chunked-prefill-size 4096`

the model I am using is https://huggingface.co/neuralmagic/Meta-Llama-3.1-405B-Instruct-FP8

I am sending requests as part of the MMLU bench https://github.com/sgl-project/sglang/tree/main/benchmark/mmlu

**Comment by Lzhang-hub** [comment] 2024-09-05 02:40
It may be cuased by set both `--disable-radix-cache` and `--chunked-prefill-size`

I test with  `--disable-radix-cache` or  `--chunked-prefill-size -1`,it can be work fine.

There warning log when start server, it seems a experimental feature.
```
You set both `--disable-radix-cache` and `--chunked-prefill-size`. This combination is an experimental feature and we noticed it can lead to wrong generation results. If you want to use chunked prefill, it is recommended not using `--disable-radix-cache`.
```

**Comment by dmakhervaks** [comment] 2024-09-05 03:59
@Lzhang-hub thanks for your reply! I tried with just `--disable-radix-cache`

i.e. like this `python3 -m sglang.launch_server --model-path $model_arg --tp 8 --disable-radix-cache --host 0.0.0.0 --port 9942 --log-level debug --file-storage-pth /home/dave.makhervaks/SGl
ang_storage`

and I still get:
![image](https://github.com/user-attachments/assets/225de5a1-5687-409e-9cdc-5b70368f6eb9)

**Comment by Lzhang-hub** [comment] 2024-09-05 04:03
when use --disable-radix-cache ,you should add `--chunked-prefill-size -1`, because sglang enable chunked-prefill default

**Comment by dmakhervaks** [comment] 2024-09-05 12:32
@Lzhang-hub thanks for your reply! That seemed to have fix it. 

Now I am seeing a discrepancy however in hellaswag results. When I run it with the following command:

`python3 bench_sglang.py --host http://10.20.45.10 --port 9942 --num-shot 10 --num-questions 10042
`
I get:

`{"task": "hellaswag", "backend": "srt", "num_gpus": 1, "latency": 3303.519, "accuracy": 0.256, "num_requests": 10042, "other": {"num_questions": 10042, "parallel": 64}}`

Which is way lower than what they quote here: https://huggingface.co/neuralmagic/Meta-Llama-3.1-405B-Instruct-FP8#accuracy

**Comment by ispobock** [comment] 2024-09-07 11:11
Same issue as https://github.com/sgl-project/sglang/pull/1304#issuecomment-2324917521. It seems that the space to allocate for `batch_prefill_tmp_v` and `batch_prefill_tmp_s` is too large (exceeds the default `flashinfer_workspace_size`: 384MB). 

https://github.com/flashinfer-ai/flashinfer/blob/46ec89317fb112dfb04bc740e711ccd3cdcf96f8/include/flashinfer/attention/handler.cuh#L797

I'm not sure why the required flashinfer space is too large for some settings.

cc: @zhyncs @yzh119 @hnyls2002

**Comment by dmakhervaks** [comment] 2024-09-08 00:50
@ispobock thanks for looping this in.

However, I do not think this should have something to do with the very bad results I am getting on Hellaswag right?

**Comment by ispobock** [comment] 2024-09-08 13:15
@dmakhervaks Did you test it on other datasets? gsm8k or mmlu?

**Comment by dmakhervaks** [comment] 2024-09-10 22:39
@ispobock These are the results I have gathered for various different models.

**MMLU**

Model | Nshot | Accuracy
Meta-Llama-3.1-8B-Instruct | 0 | 0.684
Meta-Llama-3.1-8B-Instruct | 5 | 0.682
Meta-Llama-3.1-70B-Instruct | 0 | 0.825
Meta-Llama-3.1-70B-Instruct | 5 | 0.825
Meta-Llama-3.1-405B-Instruct-FP8 | 0 | 0.864
Meta-Llama-3.1-405B-Instruct-FP8 | 5 | 0.865
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 0 | 0.861
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 5 | 0.862

**GSMK8**

MODEL | NSHOT | ACCURACY
Meta-Llama-3.1-8B-Instruct | 0 | 0.36
Meta-Llama-3.1-8B-Instruct | 5 | 0.752
Meta-Llama-3.1-8B-Instruct | 8 | 0.801
Meta-Llama-3.1-70B-Instruct | 0 | 0.810
Meta-Llama-3.1-70B-Instruct | 5 | 0.929
Meta-Llama-3.1-70B-Instruct | 8 | 0.939
Meta-Llama-3-1-405B-Instruct-FP8 | 0 | 0.879
Meta-Llama-3-1-405B-Instruct-FP8 | 5 | 0.956
Meta-Llama-3-1-405B-Instruct-FP8 | 8 | 0.961
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 0 | 0.88
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 5 | 0.958
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 8 | 0.961

**Hellaswag**

Meta-Llama-3.1-8B-Instruct | 0 | 0.315
Meta-Llama-3.1-8B-Instruct | 10 | 0.396
Meta-Llama-3.1-70B-Instruct | 0 | 0.264
Meta-Llama-3.1-70B-Instruct | 10 | 0.252
Meta-Llama-3-1-405B-Instruct-FP8 | 0 | 0.265
Meta-Llama-3-1-405B-Instruct-FP8 | 10 | 0.248
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 0 | 0.264
neuralmagic-Meta-Llama-3.1-405B-Instruct-FP8 | 10 | 0.256


None of these results match the quoted results from their HF pages, however Hellaswag achieves very poor results. Any ideas?

**Comment by ispobock** [comment] 2024-09-14 12:30
@dmakhervaks could you try to remove the `--disable-radix-cache` when testing Hellaswag?

**Comment by ispobock** [comment] 2024-09-15 15:33
> None of these results match the quoted results from their HF pages, however Hellaswag achieves very poor results.

@dmakhervaks The issue is fixed in https://github.com/sgl-project/sglang/pull/1428.

**Closed** 2024-09-15 15:35 UTC
Labels: unable-reproduce

**Comment by dmakhervaks** [comment] 2024-09-16 16:53
@ispobock why would disabling radix cache when testing hellaswag fix this issue? Does disabling radix cache somehow compromise integrity of calculations?

**Comment by ispobock** [comment] 2024-09-17 00:42
@dmakhervaks The issue was fixed without disabling the radix cache. You can check the PR mentioned above for more detail. Pls try the newest SGLang version 0.3.1.
