### ISSUE TITLE
'Runtime' object has no attribute 'cache_prefix'

### ISSUE THREAD

**Issue by gblazex** [sgl-project/sglang#88] opened 2024-01-23 16:59 UTC
`
runtime = sgl.Runtime(model_path="lmsys/vicuna-13b-v1.5")
`

```
Traceback (most recent call last):
  File "/root/test_sg.py", line 42, in <module>
    states = single_question.run_batch(
  File "/usr/local/lib/python3.10/dist-packages/sglang/lang/ir.py", line 178, in run_batch
    return run_program_batch(
  File "/usr/local/lib/python3.10/dist-packages/sglang/lang/interpreter.py", line 79, in run_program_batch
    pin_program(program, backend)
  File "/usr/local/lib/python3.10/dist-packages/sglang/lang/interpreter.py", line 132, in pin_program
    prefix_rid = backend.cache_prefix(prefix)
AttributeError: 'Runtime' object has no attribute 'cache_prefix'
```

How to fix this error?

(also how can I point it to existing cached models by say transformers
e.g. `~/.cache/huggingface/hub/models--lmsys--vicuna-13b-v1.5`)

**Comment by merrymercy** [comment] 2024-01-23 22:11
Fixed by this https://github.com/sgl-project/sglang/commit/7358fa64f7da3f18ce7512148d330755b0c1f1fe. Could you try the latest main branch?

For your question, I think the runtime will look into the cache first by default. Did you find it redownload the weights?

**Comment by isaac-vidas** [comment] 2024-01-23 23:20
Encountered this yesterday, seems to be working when I'm running it from the main branch:

<img width="1277" alt="image" src="https://github.com/sgl-project/sglang/assets/80056737/d29c5d9c-5bee-4f78-b3dd-c3207356c913">

Getting these llava image encoding errors but I don't think it's related to this issue.

**Comment by merrymercy** [comment] 2024-01-23 23:40
@isaac-vidas Does your error still occur with the main branch? Could you successfully run this example https://github.com/sgl-project/sglang/tree/main/benchmark/llava_bench?
If your error still occurs. could you provide a minimal reproducible example?

**Comment by isaac-vidas** [comment] 2024-01-24 00:00
Yes, this error is from the main branch.

Let me try to run the benchmark script and get back to you.

**Comment by isaac-vidas** [comment] 2024-01-24 01:42
I ran the benchmark script with the following output:

```console
~/sglang/benchmark/llava_bench$ python3 bench_sglang.py --num-questions 60
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 60/60 [00:19<00:00,  3.14it/s]
Latency: 19.775
Write output to answers.jsonl
```

This is the output of the `result.json` file:
```json
{"task": "llava_bench", "backend": "srt", "num_gpus": 1, "latency": 19.775, "num_requests": 60, "parallel": 64}
```

Since parallel is set to 64, the script used `run_batch` to produce the results and I didn't see any of the `RuntimeError in llava image encoding: The expanded size of the tensor (0) must match the existing size (576) at non-singleton dimension 0.  Target sizes: [0, 5120].  Tensor sizes: [576, 5120]` error I encountered with my run so I think it's something to do with my data or parameters I was using. I'll debug further on my side.

**Comment by isaac-vidas** [comment] 2024-01-24 01:54
I even tried to increase the questions of the benchmark to 6000 and run with the 13b llava model and it still runs properly. I'm pretty sure it's something with my data with prompts or images.

**Comment by merrymercy** [comment] 2024-01-24 12:05
Close this one as issues are resolved.

**Closed by merrymercy** 2024-01-24 12:05 UTC

**Comment by lockon-n** [comment] 2024-03-04 15:18
> Encountered this yesterday, seems to be working when I'm running it from the main branch:
> 
> <img alt="image" width="1277" src="https://private-user-images.githubusercontent.com/80056737/299129173-d29c5d9c-5bee-4f78-b3dd-c3207356c913.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NjU2NjcsIm5iZiI6MTcwOTU2NTM2NywicGF0aCI6Ii84MDA1NjczNy8yOTkxMjkxNzMtZDI5YzVkOWMtNWJlZS00Zjc4LWIzZGQtYzMyMDczNTZjOTEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDE1MTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MjJiYmI2Zjc1YjZlMTI0NzIyNTUyZGRlODZmYTNlNzY4MmY5ZTNjOWYxYWNkMGQyMzkwN2NhNTFlM2I5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n5CGMwIF0STD4MT4LuDDTqiXA4dPM7T4SjvSMZpW8oU">
> Getting these llava image encoding errors but I don't think it's related to this issue.

Hi @isaac-vidas , have you fixed this bug? If Yes, can you share the debugging processes and results? Thanks in advance!

**Comment by aliencaocao** [comment] 2024-03-10 16:36
Same issue with the image encoding error..
